# Data Configuration
data:
  raw_data_path: "data/raw"
  processed_data_path: "data/processed"
  cache_path: "data/cache"
  satellite_images:
    image_size: [64, 64]
    sequence_length: 24
    channels: 1
  meteorological:
    features:
      - temperature
      - humidity
      - wind_speed
      - wind_direction
      - pressure
      - precipitation
  train_test_split: 0.8
  validation_split: 0.2
  batch_size: 32

# Model Configuration
model:
  architecture:
    satellite_branch:
      conv_lstm_filters: [32, 64, 64]
      dense_units: [32, 16]
    meteo_branch:
      lstm_units: [32, 16]
      dense_units: [16, 8]
    combined:
      dense_units: [32, 16]
      dropout_rate: 0.2
  training:
    optimizer: adam
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [accuracy]
    epochs: 50
    callbacks:
      early_stopping:
        patience: 5
        restore_best_weights: true
      reduce_lr:
        factor: 0.2
        patience: 3
      model_checkpoint:
        save_best_only: true
      tensorboard:
        histogram_freq: 1
  evaluation:
    test_size: 0.2
    random_state: 42

# Logging Configuration
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  date_format: "%Y-%m-%d %H:%M:%S"
  file: "logs/rain_prediction.log"
  max_size: 10485760  # 10MB
  backup_count: 5

# Error Handling
error_handling:
  max_retries: 3
  retry_delay: 5
  raise_exceptions: true

# Paths
paths:
  models: "models"
  results: "results"
  visualizations: "visualizations"
  logs: "logs"
  checkpoints: "checkpoints" 